CEF_PASS_HOME=..
LOGS_FOLDER=$CEF_PASS_HOME/../_logs
APP_JAR=$CEF_PASS_HOME/app/build/libs/cefpass-0.1.0.jar  

CEH_FOLDER=C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/_TEST_SAMPLES/MULTI_LEVEL_INCLUDES,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/EDI,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/EFW,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/PEACE
CEF_FILE=C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111009_V01.cef.gz

java -jar $APP_JAR -h

