/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'sp' at '19/07/14 22:43' with Gradle 1.12
 *
 * @author sp, @date 19/07/14 22:43
 */

import spock.lang.Specification

import cefpass.App


class AppTest extends Specification{
    def "First Test: App.m1"() {
        setup:
        App app = new App()
        when:
        def result = app.m1()
        then:
        result == true
    }
}
