/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'sp' at '19/07/14 22:43' with Gradle 1.12
 *
 * @author sp, @date 19/07/14 22:43
 */

import spock.lang.Specification

import cefpass.App


class I_AppTest extends Specification{

//x     def TEST_SEARCH_FOLDERS = [
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/_TEST_SAMPLES/MULTI_LEVEL_INCLUDES",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/EDI",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/EFW",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/PEACE"
//x     ]
//x 
//x     def TEST_FILES = [
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111009_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111009_V01.cef",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111020_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111021_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111022_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_QZC__20111009_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_QZC__20111020_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_QZC__20111021_V01.cef.cef",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_QZC__20111021_V01.cef.gz",
//x         "C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_QZC__20111022_V01.cef.gz"
//x     ]
//x 
//x     def "First Test (args): App.stages"() {
//x     
//x         setup:
//x             def App app = new App()
//x             String[] l_args = [
//x                 "-f",
//x                 //x TEST_FILES[0],
//x                 TEST_FILES[1],          // had to add a END_OF_RECORD_MARKER = ""
//x                 "-i",
//x                 TEST_SEARCH_FOLDERS.join(","),
//x                 "-l",
//x                 "C:/work.dev/2015.03.22 github cef pass v2/v0/_logs"
//x             ]
//x         when:
//x //x             def result = app.stages(l_args)
//x             result = true
//x         then:
//x             result == true
//x     }
}
