/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'sp' at '19/07/14 22:43' with Gradle 1.12
 *
 * @author sp, @date 19/07/14 22:43
 */

import spock.lang.Specification

import cefpass.App

class RuleSet00_Tests extends Specification{

    def "RuleSet00_00 - warm-up read file only"() {
    
        setup:
            String l_path = this.getClass().getResource('RuleSet00_00/C3_CP_EDI_EGD__20111009_V01.cef')
        when:
            println "RuleSet00_00_Tests: " + l_path
            def result = (l_path != null)
        then:
            result == true
    }
    
    
    def "RuleSet00_00 - warm-up small file no errors"() {
    
        setup:
            String l_path = this.getClass().getResource('RuleSet00_00/C3_CP_EDI_EGD__20111009_V01.cef')
            l_path = l_path.substring(8)
            println(l_path)
            //x String l_path = "C:/work.dev/2015.03.22%20github%20cef%20pass%20v2/v0/cef-pass/app/build/resources/test/RuleSet00_00/C3_CP_EDI_EGD__20111009_V01.cef"
        
            def App app = new App()
            String[] l_args = [
                "-f",
                l_path,
//x             TEST_FILES[0],
//x             "-i",
//x             TEST_SEARCH_FOLDERS.join(","),
                "-l",
                "C:/work.dev/2015.03.22 github cef pass v2/v0/_logs"
            ]
        
        when:
            def result = app.stages(l_args)
        then:
            result == true
    }
    
    
}
