/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'sp' at '19/07/14 22:43' with Gradle 1.12
 *
 * @author sp, @date 19/07/14 22:43
 */

import spock.lang.Specification

import cefpass.App
import rules2015.RuleSet99

class RuleSet99_Test extends Specification{

    def SOME_TEST_DATA = "Hello, World!"

    def "RuleSet99_Test: 01"() {
    
        setup:
            RuleSet99 rs99 = new RuleSet99()
        when:
            def result = rs99.Rule_99_01()
        then:
            result == true
    }
    
    def "RuleSet99_Test: 02"() {
    
        setup:
            RuleSet99 rs99 = new RuleSet99()
        when:
            def result = rs99.Rule_99_02()
        then:
            result == true
    }
}
