gradle build & java -jar ./build/libs/cefpass-0.1.0.jar -f C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/EDI/C3_CP_EDI_EGD__20111009_V01.cef.gz -i C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/CEF/_TEST_SAMPLES/MULTI_LEVEL_INCLUDES,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/EDI,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/EFW,C:/_CEF_CEH_EXAMPLES_2013_VALIDATOR_/HEADERS/PEACE -l C:/work.dev/2014.09.27.github.cef.pass.v2/cef-pass/logs & pause




